# Ссылки на базовые переменные
$mainMod = SUPER
$terminal = kitty
$fileManager = dolphin
$menu = wofi --show drun
env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots

# Настройки для видеокарты AMD RX 5700 XT (Navi)
env = WLR_NO_HARDWARE_CURSORS,1
env = AMD_DEBUG,nongg,nodisplaylist
env = RADV_DEBUG,nohiz,nosb
env = GS_DEBUG,force_glsl

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, C, killactive,
bind = $mainMod, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, R, exec, $menu
bind = $mainMod SHIFT, P, movecurrentworkspacetomonitor, +1
bind = $mainMod, P, focusmonitor, +1
bindm = $mainMod, mouse:273, resizewindow
bind = $mainMod SHIFT, left, movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up, movewindow, u
bind = $mainMod SHIFT, down, movewindow, d
bind = $mainMod SHIFT, S, exec, systemctl suspend

# настройка скриншотов
bind = , Print, exec, hyprshot -m output 

# Выделить область для скриншота
bind = SHIFT, Print, exec, hyprshot -m region 




input {
    kb_layout = us,ru
    kb_variant = 
    kb_model = 
    kb_options = grp:win_space_toggle
    sensitivity = -0.8
}

# Мониторы
#monitor = DP-2, 1920x1080@60, 0x0, 1.25
#monitor = HDMI-A-1, 1366x768@75, auto-right, 1.0

# Автозапуск обоев и панели
exec-once = killall mpvpaper; mpvpaper -o "loop" '*' "/home/arch/Downloads/Anime Gifs Wallpaper Pc HD.gif"
exec-once = waybar
exec-once = /usr/lib/polkit-kde-authentication-agent-1

xwayland {
	force_zero_scaling = true
}

# Внешний вид окон
general {
    border_size = 2
    gaps_in = 5
    gaps_out = 6
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)
    layout = dwindle
}

# Декорации и глобальное размытие (Добавлено скругление!)
decoration {
    rounding = 12
    blur {
        enabled = true
        size = 6
        passes = 3
        new_optimizations = true
    }
}

# Эстетика для Win+R (Wofi) — исправленный синтаксис для плашки сверху
layerrule = match:namespace ^(wofi)$, blur 1
layerrule = match:namespace ^(wofi)$, ignore_alpha 0.5

windowrule = fullscreen 1, match:class ^(cs2)$
windowrule = immediate 1, match:class ^(cs2)$
